src/app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from django.conf.urls import include,url

from . import apis

app_name = 'app'
urlpatterns = [
    path('', views.FirstIndexView.as_view(), name='index'),
    path('list', views.IndexView.as_view(), name='list'),
    # path('genre', views.GenreView.as_view(), name='genre'),
    path('list/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('list/<int:pk>/rec', views.RecView.as_view(), name='rec'),
    path('api/', apis.api.as_view(), name = "api"),
    path('api/<int:pk>', apis.api_key.as_view(), name = "api_key"),
]

src/mainproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

src/app/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Genre(models.Model):
    """ジャンルマスタ"""
    name = models.CharField(max_length=30,unique=True)
    en_name = models.CharField(max_length=30)

    def __str__(self):
        return self.name;

class Studio(models.Model):
    """スタジオマスタ"""
    name = models.CharField(max_length=50,unique=True)
    en_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name;

class Media(models.Model):
    """メディアマスタ"""
    name = models.CharField(max_length=10,unique=True)

    def __str__(self):
        return self.name;

class Year(models.Model):
    """年マスタ"""
    num = models.IntegerField(unique=True)

    def __str__(self):
        return self.num;
    
class Season(models.Model):
    """季節マスタ"""
    name = models.CharField(max_length=10,unique=True)
    en_name = models.CharField(max_length=10)

    def __str__(self):
        return self.name;

class Source(models.Model):
    """原作マスタ"""
    name = models.CharField(max_length=30,unique=True)
    en_name = models.CharField(max_length=30)

    def __str__(self):
        return self.name;
    
class Anime(models.Model):
    """アニメテーブル"""
    anime_id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    en_title = models.CharField(max_length=200)
    media = models.ForeignKey(Media, on_delete=models.SET_NULL,null=True)
    episodes = models.IntegerField()
    rating = models.FloatField()
    members =  models.IntegerField()
    year = models.ForeignKey(Year, on_delete=models.SET_NULL,null=True)
    season = models.ForeignKey(Season, on_delete=models.SET_NULL,null=True)
    source = models.ForeignKey(Source, on_delete=models.SET_NULL,null=True)
    synopsis = models.TextField()
    website = models.URLField()
    image_path = models.CharField(max_length=400)

    def __str__(self):
        return self.anime_id;

class Genres(models.Model):
    """ジャンルテーブル"""
    anime_id = models.ForeignKey(Anime, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.anime_id;

class Studios(models.Model):
    """スタジオテーブル"""
    anime_id = models.ForeignKey(Anime, on_delete=models.CASCADE)
    studio = models.ForeignKey(Studio, on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.anime_id;

class Utility(models.Model):
    key = models.CharField(max_length=100)
    value = models.CharField(max_length=100)

    def __str__(self):
        return self.key;

src/app/forms.py
from django import forms
from .models import Anime

class SearchForm(forms.Form):
    title = forms.CharField(
        initial='',
        label='タイトル',
        required = False, # 必須ではない
    )
    members = forms.IntegerField(
        initial='',
        label='登録者(上)',
        required=False,  # 必須ではない
    )
    rating = forms.FloatField(
        initial='',
        label='評価スコア(上)',
        required=False,  # 必須ではない
    )

src/app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Genre, Anime, Genres, Utility
from .forms import SearchForm
from django.db.models import Q

import joblib
from sklearn.neighbors import KNeighborsClassifier
import scipy

from gensim.models import KeyedVectors

class FirstIndexView(generic.TemplateView):
    template_name = 'index.html'

class IndexView(generic.ListView):
    model = Anime
    template_name = 'list.html'
    context_object_name = 'anime_list'
    paginate_by = 50
    
    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get('title', None),
            self.request.POST.get('members', None),
            self.request.POST.get('rating', None),
        ]
        request.session['form_value'] = form_value
        # 検索時にページネーションに関連したエラーを防ぐ
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        return self.get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # sessionに値がある場合、その値をセットする。（ページングしてもform値が変わらないように）
        title = ''
        members = ''
        rating = ''
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            members = form_value[1]
            rating = form_value[2]
        default_data = {'title': title,  # タイトル
                        'members': members,  # 登録者
                        'rating': rating,  # 評価
                        }
        test_form = SearchForm(initial=default_data) # 検索フォーム
        context['test_form'] = test_form
        return context
    
    def get_queryset(self):
        # sessionに値がある場合、その値でクエリ発行する。
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            members = form_value[1]
            rating = form_value[2]
            # 検索条件
            condition_title = Q()
            condition_members = Q()
            condition_rating = Q()
            if len(title) != 0 and title[0]:
                condition_title = Q(title__icontains=title)
            if len(members) != 0 and members[0]:
                condition_members = Q(members__gt=members)
            if len(rating) != 0 and rating[0]:
                condition_rating = Q(rating__gt=rating)
            return Anime.objects.select_related().filter(condition_title & condition_members & condition_rating)
        else:
            # 全て返す
            return Anime.objects.all()
    

class RecView(generic.ListView):
    template_name = 'rec_list.html'
    context_object_name = 'rec_list'
    paginate_by = 10
    
    def get_queryset(self):
        # モデルの読み込み
        #knn_model = joblib.load('static/model/knn_model.sav')
        text = str(self.kwargs['pk'])
        model = KeyedVectors.load_word2vec_format("static/model/myanimelist_user_word2vec.txt")
        rec_list = model.most_similar(positive=text, topn=10)
        rec_list = [int(i[0]) for i in rec_list]
        #return Anime.objects.all()
        return Anime.objects.filter(anime_id__in=rec_list)
    
class DetailView(generic.DetailView):
    model = Anime
    template_name = 'detail.html'

src/app/templates/detail.html
{% load static %}

<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'app_css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'pj_image/r.png' %}" type="image/vnd.microsoft.icon">
</head>

<body>
<h1>{{ anime.title }}</h1>
<h2><img src="{{ anime.image_path }}" alt="{{ anime.title }}のイメージ" title="{{ anime.title }}のイメージ" width="280" height="384"></h2>
<h2>メディア：{{ anime.media }}</h2>
<h2>エピソード数：{{ anime.episodes }}</h2>
<h2>評価：{{ anime.rating }}</h2>
<h2>登録者：{{ anime.members }}人</h2>
<h3>年：{{ anime.year.num }}</h3>
<h3>季節：{{ anime.season }}</h3>
<h3>原作 : {{ anime.source }}</h3>
{% for gen in anime.genres_set.all %}
    <p>{{ gen.genre }}</p>
{% endfor %}
<h4>{{ anime.synopsis }}</h4>
<!-- <h2>ジャンル：{{ anime.related_genres.all }}</h2> -->
<h4>サイト：<a href="{{ anime.website }}">{{ anime.website }}</a>
<h2><a href="{% url 'app:rec' anime.anime_id %}">このアニメを見た人におすすめのアニメ</a></h2>
<a href="{% url 'app:list' %}">戻る</a>
</body>
</html>

src/app/templates/index.html
{% load static %}

<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'app_css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'pj_image/fav.png' %}" type="image/vnd.microsoft.icon">
</head>

<body>
    <h1>索引</h1>
    <a href="{% url 'app:list' %}">アニメリスト</a>
    <!-- <a href="{% url 'app:genre' %}">ジャンルリスト</a> -->
</body>
</html>

src/app/templates/list.html
{% load static %}

<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'app_css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'pj_image/r.png' %}" type="image/vnd.microsoft.icon">
</head>
<body>
<h1>アニメデータベース</h1>
<!-- formを追加 -->
<h2>アニメ検索フォーム</h2>
<form method="POST">
    {% csrf_token %}
    {% for field in test_form %}
        <div>
            {{ field.label }}:
            <div>
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <input type="submit" id="button" name="button" value="検索">
</form>
  
<table border="1">
  <thead>
    <tr>
      <th>イメージ</th>
      <th>タイトル</th>
      <th>メディア</th>
      <th>原作</th>
      <th>評価</th>
      <th>ジャンル</th>
      <th>登録者</th>
      <th>季節</th>
      <th>サイト</th>
    </tr>
  </thead>
  <tbody>
  {% for anime in anime_list %}
    <tr>
      <td><a href="{% url 'app:rec' anime.anime_id %}"><img src="{{ anime.image_path }}" alt="{{ anime.title }}のイメージ" title="{{ anime.title }}のイメージ" width="140" height="192"></a></td>
      <td><a href="{% url 'app:detail' anime.anime_id %}">{{ anime.title }}</a></td>
      <td>{{ anime.media }}</td>
      <td>{{ anime.source }}</td>
      <td>{{ anime.rating }}</td>
      <td>
      {% for gen in anime.genres_set.all %}
        <p>{{ gen.genre }}</p>
      {% endfor %}
    </td>
      <td>{{ anime.members }}</td>
      <td>{{ anime.season }}</td>
      <td><a href="{{ anime.website }}">{{ anime.website }}</a></td>
    </tr>  
  {% endfor %}
  </tbody>
</table>

<br>
<!-- ページング処理の部分 -->
<!-- 「前へ」の部分 -->
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字部分 -->
{% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
        <span>{{ num }}</span>
    {% else %}
        <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
{% endfor %}

<!-- 「次へ」 の部分 -->
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}
</body>
</html>

src/app/templates/rec_list.html
{% load static %}

<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'app_css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'pj_image/r.png' %}" type="image/vnd.microsoft.icon">
</head>
<body>
<h1>おすすめアニメ</h1>
<table border="1">
  <thead>
    <tr>
      <th>イメージ</th>
      <th>タイトル</th>
      <th>メディア</th>
      <th>原作</th>
      <th>評価</th>
      <th>ジャンル</th>
      <th>登録者</th>
      <th>季節</th>
      <th>サイト</th>
    </tr>
  </thead>
  <tbody>
  {% for anime in rec_list %}
    <tr>
      <td><img src="{{ anime.image_path }}" alt="{{ anime.title }}のイメージ" title="{{ anime.title }}のイメージ" width="140" height="192"></td>
      <td><a href="{% url 'app:detail' anime.anime_id %}">{{ anime.title }}</a></td>
      <td>{{ anime.media }}</td>
      <td>{{ anime.source }}</td>
      <td>{{ anime.rating }}</td>
      <td>
      {% for gen in anime.genres_set.all %}
        <p>{{ gen.genre }}</p>
      {% endfor %}
    </td>
      <td>{{ anime.members }}</td>
      <td>{{ anime.season }}</td>
      <td><a href="{{ anime.website }}">{{ anime.website }}</a></td>
    </tr>  
  {% endfor %}
  </tbody>
</table>
<a href="{% url 'app:list' %}">最初に戻る</a>
</body>
</html>